name: Docker Compose CI

on:
  push:
  workflow_dispatch:

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ›’ Checkout repository
        uses: actions/checkout@v3

      - name: ðŸŸ¢ Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: ðŸ“¦ Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: ðŸ§¹ Lint frontend code
        run: |
          cd frontend
          npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ›’ Checkout repository
        uses: actions/checkout@v3

      - name: ðŸŸ¢ Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      # Backend tests
      - name: ðŸ“¦ Install backend dependencies
        run: |
            cd backend
            npm install

      - name: ðŸ§ª Run backend tests
        run: |
            cd backend
            npm test

        # Frontend tests
      - name: ðŸ“¦ Install frontend dependencies
        run: |
            cd frontend
            npm install

      - name: ðŸ§ª Run frontend tests
        run: |
            cd frontend
            npm test


  build-and-push:
    runs-on: ubuntu-latest
    needs: [test] # only run if tests pass

    steps:
      - name: ðŸ›’ Checkout repository
        uses: actions/checkout@v3

      - name: ðŸ”‘ Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: mperaya
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: ðŸ›  Build and push Docker images
        env:             
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          IRON_SESSION_COOKIE_NAME: ${{ secrets.IRON_SESSION_COOKIE_NAME }}
          IRON_SESSION_PASSWORD: ${{ secrets.IRON_SESSION_PASSWORD }}
        run: |
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml push
